name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout the code

    - uses: docker/setup-buildx-action@v3
      name: Set up Docker Buildx

    - name: Login to Docker Hub
      users: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/express-htmx:latest
